version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: neverknow
      RABBITMQ_DEFAULT_PASS: neverknow
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data: 
  rabbitmq_log:

networks:
  rabbitmq_network:
    driver: bridge
